package org.geoazul.erp;
// Generated 21 de fev de 2021 12:25:46 by Hibernate Tools 5.2.11.Final

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedQuery;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

import org.geoazul.model.Address;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Cities generated by hbm2java
 */
@Entity
@Table(name = "erp_cities")


@NamedQuery(name = Cities.FIND_BY_STATE, query = "SELECT c FROM Cities c where c.states.id = :state ORDER BY c.name")
@NamedQuery(name = Cities.FIND_BY_NAME, query = "SELECT c FROM Cities c where c.name = :name")

public class Cities implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public static final String FIND_BY_STATE = "Cities.findByState";
	public static final String FIND_BY_NAME = "Cities.findByName";
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private int id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country_id", nullable = false)
	@JsonIgnore
	private Countries countries;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "state_id", nullable = false)
	@JsonIgnore
	private States states;
	
	@Column(name = "name", nullable = false)
	private String name;
	
	@Column(name = "state_code", nullable = false)
	private String stateCode;
	
	@Column(name = "country_code", nullable = false, length = 2)
	private String countryCode;
	
	@Column(name = "latitude", nullable = false, precision = 10)
	private BigDecimal latitude;
	
	@Column(name = "longitude", nullable = false, precision = 11)
	private BigDecimal longitude;
	

	@Column(name = "created_at")
	private LocalDateTime createdAt;
	

	@Column(name = "updated_at")
	private LocalDateTime updatedAt;
	
	@Column(name = "flag", nullable = false)
	private boolean flag;
	
	@Column(name = "wikidataid")
	private String wikidataid;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	@JsonIgnore
	private Set<Address> address = new HashSet<Address>(0);
		
	public Cities() {
	}

	public Cities(int id, Countries countries, States states, String name,
			String stateCode, String countryCode, BigDecimal latitude,
			BigDecimal longitude, LocalDateTime createdAt, boolean flag) {
		this.id = id;
		this.countries = countries;
		this.states = states;
		this.name = name;
		this.stateCode = stateCode;
		this.countryCode = countryCode;
		this.latitude = latitude;
		this.longitude = longitude;
		this.createdAt = createdAt;
		this.flag = flag;
	}
	public Cities(int id, Countries countries, States states, String name,
			String stateCode, String countryCode, BigDecimal latitude,
			BigDecimal longitude, LocalDateTime createdAt, LocalDateTime updatedAt, boolean flag,
			String wikidataid) {
		this.id = id;
		this.countries = countries;
		this.states = states;
		this.name = name;
		this.stateCode = stateCode;
		this.countryCode = countryCode;
		this.latitude = latitude;
		this.longitude = longitude;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.flag = flag;
		this.wikidataid = wikidataid;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Countries getCountries() {
		return this.countries;
	}

	public void setCountries(Countries countries) {
		this.countries = countries;
	}

	public States getStates() {
		return this.states;
	}

	public void setStates(States states) {
		this.states = states;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	public LocalDateTime getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(LocalDateTime createdAt) {
		this.createdAt = createdAt;
	}

	public LocalDateTime getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(LocalDateTime updatedAt) {
		this.updatedAt = updatedAt;
	}

	public boolean isFlag() {
		return this.flag;
	}

	public void setFlag(boolean flag) {
		this.flag = flag;
	}

	public String getWikidataid() {
		return this.wikidataid;
	}

	public void setWikidataid(String wikidataid) {
		this.wikidataid = wikidataid;
	}

	public Set<Address> getAddress() {
		return address;
	}

	public void setAddress(Set<Address> address) {
		this.address = address;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Cities other = (Cities) obj;
		if (id != other.id)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Cities [id=" + id + "]";
	}

}
