regex('(.*).js') -> done;
regex('(.*).map') -> done;
regex('(.*).svg') -> done;
regex('(.*).png') -> done;
regex('(.*).css') -> done;
regex('(.*).eot') -> done;
regex('(.*).woff2') -> done;
regex('(.*).woff') -> done;
regex('(.*).ttf') -> done;
regex('(.*).html') -> done;
regex('(.*).xhtml') -> done;
path-prefix('/ng')  -> rewrite('/ng/index.html')


